services:
  nanosrv:
    image: ghcr.io/devlopersabbir/nanoctrl:latest
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: nanoctrl-relay-server
    restart: unless-stopped
    ports:
      - "7443:7443/tcp"
    environment:
      - PORT=7443
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
